### ISSUE TITLE
missing secret-example.py

### ISSUE THREAD

**Issue by ghost** [SantiRey/TextClasifficationRedditTelegram#1]
Hi,

Hope you are all well !

I wanted to test your notebook in a google colab but it misses `secret.py`, which I guess must remain secret :-), but can you push an example like `secret-example.py` with dumb values ?

Cheers,
Luc

**Comment by ksreyr** [comment]
Hi Luc,

I thank you for your message, it is true an example of secret.py is a great idea. I will do it of course I will upload the example today.

have a great Week.
Santiago Rey

**Comment by ksreyr** [comment]
File added:
[File secret-example.py](https://github.com/SantiRey/TextClasifficationRedditTelegram/blob/master/secret-example.py)
